# Generated by Django 5.0.6 on 2024-06-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('postingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory', models.CharField(max_length=100)),
                ('subCategoryDesc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDetails', models.CharField(max_length=100)),
                ('postingDate', models.DateField()),
                ('postURL', models.URLField()),
                ('postImage', models.ImageField(upload_to='')),
                ('postedBy', models.CharField(max_length=100)),
                ('lastUpdatedBy', models.CharField(max_length=50)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.category')),
                ('volumeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.news_volume_issue')),
                ('subcategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subcategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.sub_category'),
        ),
    ]
