# Generated by Django 5.0.6 on 2024-07-05 09:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_category_sub_category_posts_category_subcategoryid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='postingDate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategoryID',
        ),
        migrations.AddField(
            model_name='posts',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='postTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='CategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news_volume_issue',
            name='issue',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='news_volume_issue',
            name='month_year',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='news_volume_issue',
            name='volume',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='lastUpdatedBy',
            field=models.CharField(default=datetime.date.today, max_length=50),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postDetails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(blank=True, null=True, upload_to='tmp/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postingDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='subCategoryDesc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
