# Generated by Django 5.0.6 on 2024-07-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_remove_category_postingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(blank=True, null=True, upload_to='news_app/tmp/'),
        ),
    ]
