# Generated by Django 5.0.6 on 2024-08-23 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_posts_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('postTitle', models.CharField(default='', max_length=100)),
                ('postDetails', models.TextField()),
                ('postingDate', models.DateField(default=datetime.date.today)),
                ('postImage', models.ImageField(blank=True, null=True, upload_to='news_app/tmp/')),
            ],
        ),
    ]
